version: '3.9'
services:
  postgres:
    image: postgres:17.2
    container_name: library-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: library-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
