db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5433/postgres
  hosts: localhost, 127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    com.example.spring.database.pool: INFO
    org.springframework.jdbc.core: INFO
    org.springframework.security: DEBUG
  file:
    name: application.log
    path: /

spring:
  liquibase:
    change-log: G:\projects\library_on_spring\src\main\resources\db.changelog\db.changelog-master.yaml
    enabled: false
  application:
    name:
      default: library_on_spring
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
    dbcp2:
      test-on-borrow: true
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
    open-in-view: false
