spring:
  application:
  name:
    library_on_spring: library_on_spring
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: library_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect